sudo: required
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

env:
  matrix:
    - DJANGO=1.8
    - DJANGO=1.9

install:
  - sudo apt-get install geoip-database libgeoip-dev -y
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-django${DJANGO}
  - pip install tox
  - tox -e $TOX_ENV --notest

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e $TOX_ENV -- pip install coveralls 
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION

# matrix:
#   include:
#   - python: "3.4"
#     env: ENV=docs
#     install: pip install tox
#     script: tox -e docs
